project:
  type: book

book:
  title: "Data Science Portfolio"
  author: "Lucas Melo" 
  chapters:
    - index.qmd      
    - supervised-learning.qmd     

format:
  html:
    theme: cosmo # outros temas: https://quarto.org/docs/output-formats/html-themes.html
