on:
  push:
    branches:
      - main 

name: Render and Deploy Quarto Book

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Book
        uses: quarto-dev/quarto-actions/render@v1

      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v1
        with:
          target-dir: _book
