name: Publish Quarto Book

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e "install.packages(c(
          'tidyverse', 'ggplot2', 'dplyr', 'fastDummies', 'forcats', 'readr',
          'tidymodels', 'baguette', 'tune', 'rpart', 'glmnet', 'ranger',
          'xgboost', 'kernlab', 'earth', 'nnet', 'vip', 'recipes',
          'finetune', 'workflowsets'), repos = 'https://cloud.r-project.org')"

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Book
        uses: quarto-dev/quarto-actions/render@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _book

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
